[package]
name = "xacro"
version = "0.1.3"
edition = "2021"
rust-version = "1.70"
description = "A xml preprocessor for xacro files to generate URDF files"
license = "MIT"
repository = "https://github.com/deniz-hofmeister/xacro"

[dependencies]
xml = "0.8"
xmltree = "0.12"
thiserror = "2.0"
pyisheval = "0.9"
regex = "1.12"
log = "0.4"

[dev-dependencies]
env_logger = "0.11"
similar = "2.7"
