[package]
name = "xacro"
version = "0.1.3"
edition = "2021"
rust-version = "1.70"
description = "A xml preprocessor for xacro files to generate URDF files"
license = "MIT"
repository = "https://github.com/deniz-hofmeister/xacro"

[dependencies]
xml = "0.8"
xmltree = "0.11.0"
thiserror = "2.0"
pyisheval = "0.9.0"
regex = "1.12"

[dev-dependencies]
log = "0.4.25"
env_logger = "0.11.6"
similar = "2.7.0"
